// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nano.proto

package nanoproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlocksInfoRequest struct {
	Hashes               []string `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlocksInfoRequest) Reset()         { *m = BlocksInfoRequest{} }
func (m *BlocksInfoRequest) String() string { return proto.CompactTextString(m) }
func (*BlocksInfoRequest) ProtoMessage()    {}
func (*BlocksInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11bdccbcd58847bb, []int{0}
}

func (m *BlocksInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlocksInfoRequest.Unmarshal(m, b)
}
func (m *BlocksInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlocksInfoRequest.Marshal(b, m, deterministic)
}
func (m *BlocksInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlocksInfoRequest.Merge(m, src)
}
func (m *BlocksInfoRequest) XXX_Size() int {
	return xxx_messageInfo_BlocksInfoRequest.Size(m)
}
func (m *BlocksInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlocksInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlocksInfoRequest proto.InternalMessageInfo

func (m *BlocksInfoRequest) GetHashes() []string {
	if m != nil {
		return m.Hashes
	}
	return nil
}

type Block struct {
	BlockAccount         string         `protobuf:"bytes,1,opt,name=block_account,json=blockAccount,proto3" json:"block_account,omitempty"`
	Amount               string         `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Balance              string         `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Height               string         `protobuf:"bytes,4,opt,name=height,proto3" json:"height,omitempty"`
	LocalTimestamp       string         `protobuf:"bytes,5,opt,name=local_timestamp,json=localTimestamp,proto3" json:"local_timestamp,omitempty"`
	Confirmed            string         `protobuf:"bytes,6,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	Contents             *BlockContents `protobuf:"bytes,7,opt,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_11bdccbcd58847bb, []int{1}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetBlockAccount() string {
	if m != nil {
		return m.BlockAccount
	}
	return ""
}

func (m *Block) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Block) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *Block) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

func (m *Block) GetLocalTimestamp() string {
	if m != nil {
		return m.LocalTimestamp
	}
	return ""
}

func (m *Block) GetConfirmed() string {
	if m != nil {
		return m.Confirmed
	}
	return ""
}

func (m *Block) GetContents() *BlockContents {
	if m != nil {
		return m.Contents
	}
	return nil
}

type BlockContents struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Previous             string   `protobuf:"bytes,3,opt,name=previous,proto3" json:"previous,omitempty"`
	Representative       string   `protobuf:"bytes,4,opt,name=representative,proto3" json:"representative,omitempty"`
	Balance              string   `protobuf:"bytes,5,opt,name=balance,proto3" json:"balance,omitempty"`
	Link                 string   `protobuf:"bytes,6,opt,name=link,proto3" json:"link,omitempty"`
	LinkAsAccount        string   `protobuf:"bytes,7,opt,name=link_as_account,json=linkAsAccount,proto3" json:"link_as_account,omitempty"`
	Signature            string   `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	Work                 string   `protobuf:"bytes,9,opt,name=work,proto3" json:"work,omitempty"`
	Subtype              string   `protobuf:"bytes,10,opt,name=subtype,proto3" json:"subtype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockContents) Reset()         { *m = BlockContents{} }
func (m *BlockContents) String() string { return proto.CompactTextString(m) }
func (*BlockContents) ProtoMessage()    {}
func (*BlockContents) Descriptor() ([]byte, []int) {
	return fileDescriptor_11bdccbcd58847bb, []int{2}
}

func (m *BlockContents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockContents.Unmarshal(m, b)
}
func (m *BlockContents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockContents.Marshal(b, m, deterministic)
}
func (m *BlockContents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockContents.Merge(m, src)
}
func (m *BlockContents) XXX_Size() int {
	return xxx_messageInfo_BlockContents.Size(m)
}
func (m *BlockContents) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockContents.DiscardUnknown(m)
}

var xxx_messageInfo_BlockContents proto.InternalMessageInfo

func (m *BlockContents) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *BlockContents) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *BlockContents) GetPrevious() string {
	if m != nil {
		return m.Previous
	}
	return ""
}

func (m *BlockContents) GetRepresentative() string {
	if m != nil {
		return m.Representative
	}
	return ""
}

func (m *BlockContents) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *BlockContents) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *BlockContents) GetLinkAsAccount() string {
	if m != nil {
		return m.LinkAsAccount
	}
	return ""
}

func (m *BlockContents) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *BlockContents) GetWork() string {
	if m != nil {
		return m.Work
	}
	return ""
}

func (m *BlockContents) GetSubtype() string {
	if m != nil {
		return m.Subtype
	}
	return ""
}

type BlocksInfoReply struct {
	Blocks               map[string]*Block `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BlocksInfoReply) Reset()         { *m = BlocksInfoReply{} }
func (m *BlocksInfoReply) String() string { return proto.CompactTextString(m) }
func (*BlocksInfoReply) ProtoMessage()    {}
func (*BlocksInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_11bdccbcd58847bb, []int{3}
}

func (m *BlocksInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlocksInfoReply.Unmarshal(m, b)
}
func (m *BlocksInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlocksInfoReply.Marshal(b, m, deterministic)
}
func (m *BlocksInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlocksInfoReply.Merge(m, src)
}
func (m *BlocksInfoReply) XXX_Size() int {
	return xxx_messageInfo_BlocksInfoReply.Size(m)
}
func (m *BlocksInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BlocksInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_BlocksInfoReply proto.InternalMessageInfo

func (m *BlocksInfoReply) GetBlocks() map[string]*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type ElectionInfo struct {
	Duration             string   `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration,omitempty"`
	Time                 string   `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Tally                string   `protobuf:"bytes,3,opt,name=tally,proto3" json:"tally,omitempty"`
	RequestCount         string   `protobuf:"bytes,4,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ElectionInfo) Reset()         { *m = ElectionInfo{} }
func (m *ElectionInfo) String() string { return proto.CompactTextString(m) }
func (*ElectionInfo) ProtoMessage()    {}
func (*ElectionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_11bdccbcd58847bb, []int{4}
}

func (m *ElectionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ElectionInfo.Unmarshal(m, b)
}
func (m *ElectionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ElectionInfo.Marshal(b, m, deterministic)
}
func (m *ElectionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ElectionInfo.Merge(m, src)
}
func (m *ElectionInfo) XXX_Size() int {
	return xxx_messageInfo_ElectionInfo.Size(m)
}
func (m *ElectionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ElectionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ElectionInfo proto.InternalMessageInfo

func (m *ElectionInfo) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

func (m *ElectionInfo) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *ElectionInfo) GetTally() string {
	if m != nil {
		return m.Tally
	}
	return ""
}

func (m *ElectionInfo) GetRequestCount() string {
	if m != nil {
		return m.RequestCount
	}
	return ""
}

type SubscriptionMessage struct {
	Account              string             `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Signature            string             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Sequence             string             `protobuf:"bytes,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Blocks               []string           `protobuf:"bytes,4,rep,name=blocks,proto3" json:"blocks,omitempty"`
	Amount               string             `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Hash                 string             `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
	ConfirmationType     string             `protobuf:"bytes,7,opt,name=confirmation_type,json=confirmationType,proto3" json:"confirmation_type,omitempty"`
	ElectionInfo         *ElectionInfo      `protobuf:"bytes,8,opt,name=election_info,json=electionInfo,proto3" json:"election_info,omitempty"`
	Block                *SubscriptionBlock `protobuf:"bytes,9,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SubscriptionMessage) Reset()         { *m = SubscriptionMessage{} }
func (m *SubscriptionMessage) String() string { return proto.CompactTextString(m) }
func (*SubscriptionMessage) ProtoMessage()    {}
func (*SubscriptionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_11bdccbcd58847bb, []int{5}
}

func (m *SubscriptionMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscriptionMessage.Unmarshal(m, b)
}
func (m *SubscriptionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscriptionMessage.Marshal(b, m, deterministic)
}
func (m *SubscriptionMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscriptionMessage.Merge(m, src)
}
func (m *SubscriptionMessage) XXX_Size() int {
	return xxx_messageInfo_SubscriptionMessage.Size(m)
}
func (m *SubscriptionMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscriptionMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SubscriptionMessage proto.InternalMessageInfo

func (m *SubscriptionMessage) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *SubscriptionMessage) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *SubscriptionMessage) GetSequence() string {
	if m != nil {
		return m.Sequence
	}
	return ""
}

func (m *SubscriptionMessage) GetBlocks() []string {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func (m *SubscriptionMessage) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *SubscriptionMessage) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *SubscriptionMessage) GetConfirmationType() string {
	if m != nil {
		return m.ConfirmationType
	}
	return ""
}

func (m *SubscriptionMessage) GetElectionInfo() *ElectionInfo {
	if m != nil {
		return m.ElectionInfo
	}
	return nil
}

func (m *SubscriptionMessage) GetBlock() *SubscriptionBlock {
	if m != nil {
		return m.Block
	}
	return nil
}

type SubscriptionBlock struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Representative       string   `protobuf:"bytes,3,opt,name=representative,proto3" json:"representative,omitempty"`
	Account              string   `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	Work                 string   `protobuf:"bytes,5,opt,name=work,proto3" json:"work,omitempty"`
	Signature            string   `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	Previous             string   `protobuf:"bytes,7,opt,name=previous,proto3" json:"previous,omitempty"`
	LinkAsAccount        string   `protobuf:"bytes,8,opt,name=link_as_account,json=linkAsAccount,proto3" json:"link_as_account,omitempty"`
	Subtype              string   `protobuf:"bytes,9,opt,name=subtype,proto3" json:"subtype,omitempty"`
	Link                 string   `protobuf:"bytes,10,opt,name=link,proto3" json:"link,omitempty"`
	Balance              string   `protobuf:"bytes,11,opt,name=balance,proto3" json:"balance,omitempty"`
	Destination          string   `protobuf:"bytes,12,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscriptionBlock) Reset()         { *m = SubscriptionBlock{} }
func (m *SubscriptionBlock) String() string { return proto.CompactTextString(m) }
func (*SubscriptionBlock) ProtoMessage()    {}
func (*SubscriptionBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_11bdccbcd58847bb, []int{6}
}

func (m *SubscriptionBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscriptionBlock.Unmarshal(m, b)
}
func (m *SubscriptionBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscriptionBlock.Marshal(b, m, deterministic)
}
func (m *SubscriptionBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscriptionBlock.Merge(m, src)
}
func (m *SubscriptionBlock) XXX_Size() int {
	return xxx_messageInfo_SubscriptionBlock.Size(m)
}
func (m *SubscriptionBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscriptionBlock.DiscardUnknown(m)
}

var xxx_messageInfo_SubscriptionBlock proto.InternalMessageInfo

func (m *SubscriptionBlock) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SubscriptionBlock) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *SubscriptionBlock) GetRepresentative() string {
	if m != nil {
		return m.Representative
	}
	return ""
}

func (m *SubscriptionBlock) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *SubscriptionBlock) GetWork() string {
	if m != nil {
		return m.Work
	}
	return ""
}

func (m *SubscriptionBlock) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *SubscriptionBlock) GetPrevious() string {
	if m != nil {
		return m.Previous
	}
	return ""
}

func (m *SubscriptionBlock) GetLinkAsAccount() string {
	if m != nil {
		return m.LinkAsAccount
	}
	return ""
}

func (m *SubscriptionBlock) GetSubtype() string {
	if m != nil {
		return m.Subtype
	}
	return ""
}

func (m *SubscriptionBlock) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *SubscriptionBlock) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *SubscriptionBlock) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

type SubscriptionEntry struct {
	Topic                string               `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Time                 string               `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Message              *SubscriptionMessage `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SubscriptionEntry) Reset()         { *m = SubscriptionEntry{} }
func (m *SubscriptionEntry) String() string { return proto.CompactTextString(m) }
func (*SubscriptionEntry) ProtoMessage()    {}
func (*SubscriptionEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_11bdccbcd58847bb, []int{7}
}

func (m *SubscriptionEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscriptionEntry.Unmarshal(m, b)
}
func (m *SubscriptionEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscriptionEntry.Marshal(b, m, deterministic)
}
func (m *SubscriptionEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscriptionEntry.Merge(m, src)
}
func (m *SubscriptionEntry) XXX_Size() int {
	return xxx_messageInfo_SubscriptionEntry.Size(m)
}
func (m *SubscriptionEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscriptionEntry.DiscardUnknown(m)
}

var xxx_messageInfo_SubscriptionEntry proto.InternalMessageInfo

func (m *SubscriptionEntry) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *SubscriptionEntry) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *SubscriptionEntry) GetMessage() *SubscriptionMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*BlocksInfoRequest)(nil), "nanoproto.BlocksInfoRequest")
	proto.RegisterType((*Block)(nil), "nanoproto.Block")
	proto.RegisterType((*BlockContents)(nil), "nanoproto.BlockContents")
	proto.RegisterType((*BlocksInfoReply)(nil), "nanoproto.BlocksInfoReply")
	proto.RegisterMapType((map[string]*Block)(nil), "nanoproto.BlocksInfoReply.BlocksEntry")
	proto.RegisterType((*ElectionInfo)(nil), "nanoproto.ElectionInfo")
	proto.RegisterType((*SubscriptionMessage)(nil), "nanoproto.SubscriptionMessage")
	proto.RegisterType((*SubscriptionBlock)(nil), "nanoproto.SubscriptionBlock")
	proto.RegisterType((*SubscriptionEntry)(nil), "nanoproto.SubscriptionEntry")
}

func init() { proto.RegisterFile("nano.proto", fileDescriptor_11bdccbcd58847bb) }

var fileDescriptor_11bdccbcd58847bb = []byte{
	// 792 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0xdd, 0x6a, 0xe3, 0x46,
	0x14, 0xae, 0x6c, 0xcb, 0x3f, 0x47, 0x76, 0x9c, 0x4c, 0x4b, 0x2a, 0x5c, 0x53, 0x8c, 0x0a, 0x6e,
	0x20, 0xe0, 0x0b, 0xb5, 0x94, 0x50, 0x4a, 0x21, 0x09, 0x81, 0x2c, 0xfb, 0x43, 0xd0, 0x06, 0x72,
	0x69, 0xc6, 0xf2, 0xc4, 0x16, 0x96, 0x67, 0xb4, 0x9a, 0x51, 0xb2, 0x7e, 0x99, 0xbd, 0xd8, 0x7d,
	0x9d, 0x7d, 0x89, 0x7d, 0x86, 0x7d, 0x81, 0x65, 0x7e, 0x24, 0x4b, 0x8e, 0x7d, 0xe5, 0xf3, 0x9d,
	0x33, 0x3a, 0x9e, 0xf9, 0xbe, 0xf3, 0x1d, 0x00, 0x8a, 0x29, 0x9b, 0x24, 0x29, 0x13, 0x0c, 0x75,
	0x64, 0xac, 0x42, 0xef, 0x1c, 0x4e, 0xae, 0x62, 0x16, 0xae, 0xf8, 0x2b, 0xfa, 0xc8, 0x02, 0xf2,
	0x21, 0x23, 0x5c, 0xa0, 0x53, 0x68, 0x2e, 0x31, 0x5f, 0x12, 0xee, 0x5a, 0xa3, 0xfa, 0x59, 0x27,
	0x30, 0xc8, 0xfb, 0x6e, 0x81, 0xad, 0x4e, 0xa3, 0x3f, 0xa0, 0x37, 0x93, 0xc1, 0x14, 0x87, 0x21,
	0xcb, 0xa8, 0x70, 0xad, 0x91, 0x75, 0xd6, 0x09, 0xba, 0x2a, 0x79, 0xa9, 0x73, 0xb2, 0x0d, 0x5e,
	0xab, 0x6a, 0x4d, 0x55, 0x0d, 0x42, 0x2e, 0xb4, 0x66, 0x38, 0xc6, 0x34, 0x24, 0x6e, 0x5d, 0x15,
	0x72, 0xa8, 0xfe, 0x98, 0x44, 0x8b, 0xa5, 0x70, 0x1b, 0xfa, 0x0b, 0x8d, 0xd0, 0x9f, 0xd0, 0x8f,
	0x59, 0x88, 0xe3, 0xa9, 0x88, 0xd6, 0x84, 0x0b, 0xbc, 0x4e, 0x5c, 0x5b, 0x1d, 0x38, 0x52, 0xe9,
	0xfb, 0x3c, 0x8b, 0x86, 0xd0, 0x09, 0x19, 0x7d, 0x8c, 0xd2, 0x35, 0x99, 0xbb, 0x4d, 0x75, 0x64,
	0x9b, 0x40, 0x7f, 0x43, 0x3b, 0x64, 0x54, 0x10, 0x2a, 0xb8, 0xdb, 0x1a, 0x59, 0x67, 0x8e, 0xef,
	0x4e, 0x0a, 0x2a, 0x26, 0xea, 0x65, 0xd7, 0xa6, 0x1e, 0x14, 0x27, 0xbd, 0x2f, 0x35, 0xe8, 0x55,
	0x6a, 0x08, 0x41, 0x43, 0x6c, 0x12, 0x62, 0x1e, 0xad, 0x62, 0xf9, 0xa8, 0x9c, 0x0b, 0xfd, 0xda,
	0x1c, 0xa2, 0x01, 0xb4, 0x93, 0x94, 0x3c, 0x45, 0x2c, 0xe3, 0xe6, 0xbd, 0x05, 0x46, 0x63, 0x38,
	0x4a, 0x49, 0x92, 0x12, 0x4e, 0xa8, 0xc0, 0x22, 0x7a, 0x22, 0xe6, 0xe1, 0x3b, 0xd9, 0x32, 0x65,
	0x76, 0x95, 0x32, 0x04, 0x8d, 0x38, 0xa2, 0x2b, 0xf3, 0x58, 0x15, 0xa3, 0x31, 0xf4, 0xe5, 0xef,
	0x14, 0xf3, 0x42, 0x9f, 0x96, 0x2a, 0xf7, 0x64, 0xfa, 0x92, 0xe7, 0x02, 0x0d, 0xa1, 0xc3, 0xa3,
	0x05, 0xc5, 0x22, 0x4b, 0x89, 0xdb, 0xd6, 0x6c, 0x15, 0x09, 0xd9, 0xf9, 0x99, 0xa5, 0x2b, 0xb7,
	0xa3, 0x3b, 0xcb, 0x58, 0xde, 0x83, 0x67, 0x33, 0xf5, 0x78, 0xd0, 0xf7, 0x30, 0xd0, 0xfb, 0x64,
	0x41, 0xbf, 0x3c, 0x49, 0x49, 0xbc, 0x41, 0xff, 0x43, 0x53, 0x0d, 0x84, 0x9e, 0x23, 0xc7, 0x1f,
	0xef, 0xb2, 0xbd, 0x3d, 0x6b, 0xf0, 0x0d, 0x15, 0xe9, 0x26, 0x30, 0x5f, 0x0d, 0x5e, 0x83, 0x53,
	0x4a, 0xa3, 0x63, 0xa8, 0xaf, 0xc8, 0xc6, 0xb0, 0x2e, 0x43, 0x34, 0x06, 0xfb, 0x09, 0xc7, 0x19,
	0x51, 0x94, 0x3b, 0xfe, 0xf1, 0x6e, 0xff, 0x40, 0x97, 0xff, 0xad, 0x5d, 0x58, 0xde, 0x06, 0xba,
	0x37, 0x31, 0x09, 0x45, 0xc4, 0xa8, 0xfc, 0x57, 0x29, 0xcb, 0x3c, 0x4b, 0xb1, 0xc4, 0xa6, 0x65,
	0x81, 0x95, 0xc0, 0xd1, 0x9a, 0x18, 0x25, 0x55, 0x8c, 0x7e, 0x01, 0x5b, 0xe0, 0x38, 0xde, 0x18,
	0x0d, 0x35, 0x90, 0x46, 0x48, 0xb5, 0x6b, 0xa6, 0x9a, 0x68, 0xad, 0x5f, 0xd7, 0x24, 0xaf, 0x65,
	0xce, 0xfb, 0x5a, 0x83, 0x9f, 0xdf, 0x67, 0x33, 0x1e, 0xa6, 0x51, 0x22, 0xfb, 0xbf, 0x25, 0x9c,
	0xe3, 0x45, 0x65, 0x66, 0xac, 0xea, 0xcc, 0x54, 0x94, 0xa9, 0xed, 0x2a, 0x33, 0x80, 0x36, 0x97,
	0xfd, 0xb7, 0x0e, 0x2a, 0xb0, 0xb4, 0x90, 0xe1, 0xbc, 0xa1, 0xbd, 0xab, 0x51, 0xc9, 0x8c, 0x76,
	0xc5, 0x8c, 0x08, 0x1a, 0xd2, 0xdd, 0xf9, 0xfc, 0xc8, 0x18, 0x9d, 0xc3, 0x89, 0x31, 0x8d, 0xa2,
	0x63, 0xaa, 0xf4, 0xd6, 0x13, 0x74, 0x5c, 0x2e, 0xdc, 0xcb, 0xc1, 0xff, 0x0f, 0x7a, 0xc4, 0xf0,
	0x3a, 0x8d, 0xe8, 0x23, 0x53, 0x83, 0xe4, 0xf8, 0xbf, 0x96, 0xb4, 0x28, 0xf3, 0x1e, 0x74, 0x49,
	0x59, 0x05, 0x1f, 0x6c, 0x75, 0x41, 0x35, 0x65, 0x8e, 0x3f, 0x2c, 0x7d, 0x55, 0x66, 0xcc, 0xa8,
	0xa9, 0x8e, 0x7a, 0xdf, 0x6a, 0x70, 0xf2, 0xa2, 0xb8, 0xd7, 0x94, 0xa7, 0xd0, 0xe4, 0x2c, 0x4b,
	0xc3, 0x9c, 0x43, 0x83, 0xf6, 0xd8, 0xae, 0x7e, 0xc8, 0x76, 0xb9, 0x40, 0x8d, 0xaa, 0x40, 0xb9,
	0x39, 0xec, 0x92, 0x39, 0x2a, 0xa2, 0x35, 0xf7, 0x88, 0x56, 0xac, 0x81, 0xd6, 0x8b, 0x35, 0xf0,
	0xc2, 0xb0, 0xed, 0x7d, 0x86, 0x2d, 0xd9, 0xaf, 0x53, 0xb1, 0x5f, 0xb1, 0x06, 0xa0, 0xb4, 0x06,
	0x4a, 0x4b, 0xc3, 0xa9, 0x2e, 0x8d, 0x11, 0x38, 0x73, 0xc2, 0x45, 0x44, 0xf5, 0xf8, 0x77, 0x55,
	0xb5, 0x9c, 0xf2, 0x9e, 0xab, 0x14, 0x6b, 0x03, 0x4a, 0x0b, 0xb0, 0x24, 0x0a, 0x0d, 0xc7, 0x1a,
	0xec, 0x35, 0xcb, 0x05, 0xb4, 0xd6, 0x7a, 0xc8, 0x15, 0xb3, 0x8e, 0xff, 0xfb, 0x01, 0x61, 0x8d,
	0x15, 0x82, 0xfc, 0xb8, 0x7f, 0x07, 0x8d, 0x77, 0x98, 0x32, 0x74, 0x0b, 0xb0, 0x5d, 0x11, 0x68,
	0x78, 0x60, 0x73, 0x28, 0x93, 0x0d, 0x06, 0x87, 0xf7, 0x8a, 0xf7, 0xd3, 0xd5, 0x3f, 0xf0, 0x5b,
	0xc4, 0x26, 0x8b, 0x34, 0x09, 0x27, 0xe4, 0x23, 0x5e, 0x27, 0x31, 0xe1, 0x93, 0x25, 0x89, 0x63,
	0xf6, 0xcc, 0xd2, 0x78, 0x7e, 0xd5, 0xbf, 0x95, 0xf1, 0x83, 0x8c, 0xef, 0x64, 0x87, 0x3b, 0xeb,
	0x73, 0xad, 0x7e, 0xfb, 0xe6, 0x61, 0xd6, 0x54, 0x0d, 0xff, 0xfa, 0x11, 0x00, 0x00, 0xff, 0xff,
	0xdf, 0x9c, 0xed, 0xb9, 0x3a, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NanoClient is the client API for Nano service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NanoClient interface {
	BlocksInfo(ctx context.Context, in *BlocksInfoRequest, opts ...grpc.CallOption) (*BlocksInfoReply, error)
}

type nanoClient struct {
	cc *grpc.ClientConn
}

func NewNanoClient(cc *grpc.ClientConn) NanoClient {
	return &nanoClient{cc}
}

func (c *nanoClient) BlocksInfo(ctx context.Context, in *BlocksInfoRequest, opts ...grpc.CallOption) (*BlocksInfoReply, error) {
	out := new(BlocksInfoReply)
	err := c.cc.Invoke(ctx, "/nanoproto.Nano/BlocksInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NanoServer is the server API for Nano service.
type NanoServer interface {
	BlocksInfo(context.Context, *BlocksInfoRequest) (*BlocksInfoReply, error)
}

// UnimplementedNanoServer can be embedded to have forward compatible implementations.
type UnimplementedNanoServer struct {
}

func (*UnimplementedNanoServer) BlocksInfo(ctx context.Context, req *BlocksInfoRequest) (*BlocksInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlocksInfo not implemented")
}

func RegisterNanoServer(s *grpc.Server, srv NanoServer) {
	s.RegisterService(&_Nano_serviceDesc, srv)
}

func _Nano_BlocksInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlocksInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NanoServer).BlocksInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nanoproto.Nano/BlocksInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NanoServer).BlocksInfo(ctx, req.(*BlocksInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Nano_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nanoproto.Nano",
	HandlerType: (*NanoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BlocksInfo",
			Handler:    _Nano_BlocksInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nano.proto",
}
