// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nano.proto

package nanoproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//Send
type SendRequest struct {
	Wallet               string   `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Destination          string   `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Amount               string   `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendRequest) Reset()         { *m = SendRequest{} }
func (m *SendRequest) String() string { return proto.CompactTextString(m) }
func (*SendRequest) ProtoMessage()    {}
func (*SendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11bdccbcd58847bb, []int{0}
}

func (m *SendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRequest.Unmarshal(m, b)
}
func (m *SendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRequest.Marshal(b, m, deterministic)
}
func (m *SendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRequest.Merge(m, src)
}
func (m *SendRequest) XXX_Size() int {
	return xxx_messageInfo_SendRequest.Size(m)
}
func (m *SendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendRequest proto.InternalMessageInfo

func (m *SendRequest) GetWallet() string {
	if m != nil {
		return m.Wallet
	}
	return ""
}

func (m *SendRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *SendRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *SendRequest) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type SendReply struct {
	Block                string   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendReply) Reset()         { *m = SendReply{} }
func (m *SendReply) String() string { return proto.CompactTextString(m) }
func (*SendReply) ProtoMessage()    {}
func (*SendReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_11bdccbcd58847bb, []int{1}
}

func (m *SendReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendReply.Unmarshal(m, b)
}
func (m *SendReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendReply.Marshal(b, m, deterministic)
}
func (m *SendReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendReply.Merge(m, src)
}
func (m *SendReply) XXX_Size() int {
	return xxx_messageInfo_SendReply.Size(m)
}
func (m *SendReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendReply proto.InternalMessageInfo

func (m *SendReply) GetBlock() string {
	if m != nil {
		return m.Block
	}
	return ""
}

//Validate Account Number
type ValidateAccountNumberRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateAccountNumberRequest) Reset()         { *m = ValidateAccountNumberRequest{} }
func (m *ValidateAccountNumberRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateAccountNumberRequest) ProtoMessage()    {}
func (*ValidateAccountNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11bdccbcd58847bb, []int{2}
}

func (m *ValidateAccountNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateAccountNumberRequest.Unmarshal(m, b)
}
func (m *ValidateAccountNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateAccountNumberRequest.Marshal(b, m, deterministic)
}
func (m *ValidateAccountNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateAccountNumberRequest.Merge(m, src)
}
func (m *ValidateAccountNumberRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateAccountNumberRequest.Size(m)
}
func (m *ValidateAccountNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateAccountNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateAccountNumberRequest proto.InternalMessageInfo

func (m *ValidateAccountNumberRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type ValidateAccountNumberReply struct {
	Valid                string   `protobuf:"bytes,1,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateAccountNumberReply) Reset()         { *m = ValidateAccountNumberReply{} }
func (m *ValidateAccountNumberReply) String() string { return proto.CompactTextString(m) }
func (*ValidateAccountNumberReply) ProtoMessage()    {}
func (*ValidateAccountNumberReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_11bdccbcd58847bb, []int{3}
}

func (m *ValidateAccountNumberReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateAccountNumberReply.Unmarshal(m, b)
}
func (m *ValidateAccountNumberReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateAccountNumberReply.Marshal(b, m, deterministic)
}
func (m *ValidateAccountNumberReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateAccountNumberReply.Merge(m, src)
}
func (m *ValidateAccountNumberReply) XXX_Size() int {
	return xxx_messageInfo_ValidateAccountNumberReply.Size(m)
}
func (m *ValidateAccountNumberReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateAccountNumberReply.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateAccountNumberReply proto.InternalMessageInfo

func (m *ValidateAccountNumberReply) GetValid() string {
	if m != nil {
		return m.Valid
	}
	return ""
}

//Account Create
type AccountCreateRequest struct {
	Wallet               string   `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountCreateRequest) Reset()         { *m = AccountCreateRequest{} }
func (m *AccountCreateRequest) String() string { return proto.CompactTextString(m) }
func (*AccountCreateRequest) ProtoMessage()    {}
func (*AccountCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11bdccbcd58847bb, []int{4}
}

func (m *AccountCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountCreateRequest.Unmarshal(m, b)
}
func (m *AccountCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountCreateRequest.Marshal(b, m, deterministic)
}
func (m *AccountCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountCreateRequest.Merge(m, src)
}
func (m *AccountCreateRequest) XXX_Size() int {
	return xxx_messageInfo_AccountCreateRequest.Size(m)
}
func (m *AccountCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountCreateRequest proto.InternalMessageInfo

func (m *AccountCreateRequest) GetWallet() string {
	if m != nil {
		return m.Wallet
	}
	return ""
}

type AccountCreateReply struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountCreateReply) Reset()         { *m = AccountCreateReply{} }
func (m *AccountCreateReply) String() string { return proto.CompactTextString(m) }
func (*AccountCreateReply) ProtoMessage()    {}
func (*AccountCreateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_11bdccbcd58847bb, []int{5}
}

func (m *AccountCreateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountCreateReply.Unmarshal(m, b)
}
func (m *AccountCreateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountCreateReply.Marshal(b, m, deterministic)
}
func (m *AccountCreateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountCreateReply.Merge(m, src)
}
func (m *AccountCreateReply) XXX_Size() int {
	return xxx_messageInfo_AccountCreateReply.Size(m)
}
func (m *AccountCreateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountCreateReply.DiscardUnknown(m)
}

var xxx_messageInfo_AccountCreateReply proto.InternalMessageInfo

func (m *AccountCreateReply) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

// Account Balance
type AccountBalanceRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountBalanceRequest) Reset()         { *m = AccountBalanceRequest{} }
func (m *AccountBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*AccountBalanceRequest) ProtoMessage()    {}
func (*AccountBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11bdccbcd58847bb, []int{6}
}

func (m *AccountBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountBalanceRequest.Unmarshal(m, b)
}
func (m *AccountBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountBalanceRequest.Marshal(b, m, deterministic)
}
func (m *AccountBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountBalanceRequest.Merge(m, src)
}
func (m *AccountBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_AccountBalanceRequest.Size(m)
}
func (m *AccountBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountBalanceRequest proto.InternalMessageInfo

func (m *AccountBalanceRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type AccountBalanceReply struct {
	Balance              string   `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Pending              string   `protobuf:"bytes,2,opt,name=pending,proto3" json:"pending,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountBalanceReply) Reset()         { *m = AccountBalanceReply{} }
func (m *AccountBalanceReply) String() string { return proto.CompactTextString(m) }
func (*AccountBalanceReply) ProtoMessage()    {}
func (*AccountBalanceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_11bdccbcd58847bb, []int{7}
}

func (m *AccountBalanceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountBalanceReply.Unmarshal(m, b)
}
func (m *AccountBalanceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountBalanceReply.Marshal(b, m, deterministic)
}
func (m *AccountBalanceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountBalanceReply.Merge(m, src)
}
func (m *AccountBalanceReply) XXX_Size() int {
	return xxx_messageInfo_AccountBalanceReply.Size(m)
}
func (m *AccountBalanceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountBalanceReply.DiscardUnknown(m)
}

var xxx_messageInfo_AccountBalanceReply proto.InternalMessageInfo

func (m *AccountBalanceReply) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *AccountBalanceReply) GetPending() string {
	if m != nil {
		return m.Pending
	}
	return ""
}

type AccountsBalancesRequest struct {
	Accounts             []string `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountsBalancesRequest) Reset()         { *m = AccountsBalancesRequest{} }
func (m *AccountsBalancesRequest) String() string { return proto.CompactTextString(m) }
func (*AccountsBalancesRequest) ProtoMessage()    {}
func (*AccountsBalancesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11bdccbcd58847bb, []int{8}
}

func (m *AccountsBalancesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountsBalancesRequest.Unmarshal(m, b)
}
func (m *AccountsBalancesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountsBalancesRequest.Marshal(b, m, deterministic)
}
func (m *AccountsBalancesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountsBalancesRequest.Merge(m, src)
}
func (m *AccountsBalancesRequest) XXX_Size() int {
	return xxx_messageInfo_AccountsBalancesRequest.Size(m)
}
func (m *AccountsBalancesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountsBalancesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountsBalancesRequest proto.InternalMessageInfo

func (m *AccountsBalancesRequest) GetAccounts() []string {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type Balance struct {
	Balance              string   `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Pending              string   `protobuf:"bytes,2,opt,name=pending,proto3" json:"pending,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Balance) Reset()         { *m = Balance{} }
func (m *Balance) String() string { return proto.CompactTextString(m) }
func (*Balance) ProtoMessage()    {}
func (*Balance) Descriptor() ([]byte, []int) {
	return fileDescriptor_11bdccbcd58847bb, []int{9}
}

func (m *Balance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Balance.Unmarshal(m, b)
}
func (m *Balance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Balance.Marshal(b, m, deterministic)
}
func (m *Balance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Balance.Merge(m, src)
}
func (m *Balance) XXX_Size() int {
	return xxx_messageInfo_Balance.Size(m)
}
func (m *Balance) XXX_DiscardUnknown() {
	xxx_messageInfo_Balance.DiscardUnknown(m)
}

var xxx_messageInfo_Balance proto.InternalMessageInfo

func (m *Balance) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *Balance) GetPending() string {
	if m != nil {
		return m.Pending
	}
	return ""
}

type AccountsBalancesReply struct {
	Balances             map[string]*Balance `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AccountsBalancesReply) Reset()         { *m = AccountsBalancesReply{} }
func (m *AccountsBalancesReply) String() string { return proto.CompactTextString(m) }
func (*AccountsBalancesReply) ProtoMessage()    {}
func (*AccountsBalancesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_11bdccbcd58847bb, []int{10}
}

func (m *AccountsBalancesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountsBalancesReply.Unmarshal(m, b)
}
func (m *AccountsBalancesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountsBalancesReply.Marshal(b, m, deterministic)
}
func (m *AccountsBalancesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountsBalancesReply.Merge(m, src)
}
func (m *AccountsBalancesReply) XXX_Size() int {
	return xxx_messageInfo_AccountsBalancesReply.Size(m)
}
func (m *AccountsBalancesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountsBalancesReply.DiscardUnknown(m)
}

var xxx_messageInfo_AccountsBalancesReply proto.InternalMessageInfo

func (m *AccountsBalancesReply) GetBalances() map[string]*Balance {
	if m != nil {
		return m.Balances
	}
	return nil
}

// BlockInfo Request
type BlockInfoRequest struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockInfoRequest) Reset()         { *m = BlockInfoRequest{} }
func (m *BlockInfoRequest) String() string { return proto.CompactTextString(m) }
func (*BlockInfoRequest) ProtoMessage()    {}
func (*BlockInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11bdccbcd58847bb, []int{11}
}

func (m *BlockInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockInfoRequest.Unmarshal(m, b)
}
func (m *BlockInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockInfoRequest.Marshal(b, m, deterministic)
}
func (m *BlockInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockInfoRequest.Merge(m, src)
}
func (m *BlockInfoRequest) XXX_Size() int {
	return xxx_messageInfo_BlockInfoRequest.Size(m)
}
func (m *BlockInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlockInfoRequest proto.InternalMessageInfo

func (m *BlockInfoRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type BlockInfoReply struct {
	BlockAccount         string         `protobuf:"bytes,1,opt,name=block_account,json=blockAccount,proto3" json:"block_account,omitempty"`
	Amount               string         `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Balance              string         `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Height               string         `protobuf:"bytes,4,opt,name=height,proto3" json:"height,omitempty"`
	LocalTimestamp       string         `protobuf:"bytes,5,opt,name=local_timestamp,json=localTimestamp,proto3" json:"local_timestamp,omitempty"`
	Confirmed            string         `protobuf:"bytes,6,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	Contents             *BlockContents `protobuf:"bytes,7,opt,name=contents,proto3" json:"contents,omitempty"`
	Subtype              string         `protobuf:"bytes,8,opt,name=subtype,proto3" json:"subtype,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BlockInfoReply) Reset()         { *m = BlockInfoReply{} }
func (m *BlockInfoReply) String() string { return proto.CompactTextString(m) }
func (*BlockInfoReply) ProtoMessage()    {}
func (*BlockInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_11bdccbcd58847bb, []int{12}
}

func (m *BlockInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockInfoReply.Unmarshal(m, b)
}
func (m *BlockInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockInfoReply.Marshal(b, m, deterministic)
}
func (m *BlockInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockInfoReply.Merge(m, src)
}
func (m *BlockInfoReply) XXX_Size() int {
	return xxx_messageInfo_BlockInfoReply.Size(m)
}
func (m *BlockInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_BlockInfoReply proto.InternalMessageInfo

func (m *BlockInfoReply) GetBlockAccount() string {
	if m != nil {
		return m.BlockAccount
	}
	return ""
}

func (m *BlockInfoReply) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *BlockInfoReply) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *BlockInfoReply) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

func (m *BlockInfoReply) GetLocalTimestamp() string {
	if m != nil {
		return m.LocalTimestamp
	}
	return ""
}

func (m *BlockInfoReply) GetConfirmed() string {
	if m != nil {
		return m.Confirmed
	}
	return ""
}

func (m *BlockInfoReply) GetContents() *BlockContents {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *BlockInfoReply) GetSubtype() string {
	if m != nil {
		return m.Subtype
	}
	return ""
}

type BlockContents struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Previous             string   `protobuf:"bytes,3,opt,name=previous,proto3" json:"previous,omitempty"`
	Representative       string   `protobuf:"bytes,4,opt,name=representative,proto3" json:"representative,omitempty"`
	Balance              string   `protobuf:"bytes,5,opt,name=balance,proto3" json:"balance,omitempty"`
	Link                 string   `protobuf:"bytes,6,opt,name=link,proto3" json:"link,omitempty"`
	LinkAsAccount        string   `protobuf:"bytes,7,opt,name=link_as_account,json=linkAsAccount,proto3" json:"link_as_account,omitempty"`
	Signature            string   `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	Work                 string   `protobuf:"bytes,9,opt,name=work,proto3" json:"work,omitempty"`
	Subtype              string   `protobuf:"bytes,10,opt,name=subtype,proto3" json:"subtype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockContents) Reset()         { *m = BlockContents{} }
func (m *BlockContents) String() string { return proto.CompactTextString(m) }
func (*BlockContents) ProtoMessage()    {}
func (*BlockContents) Descriptor() ([]byte, []int) {
	return fileDescriptor_11bdccbcd58847bb, []int{13}
}

func (m *BlockContents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockContents.Unmarshal(m, b)
}
func (m *BlockContents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockContents.Marshal(b, m, deterministic)
}
func (m *BlockContents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockContents.Merge(m, src)
}
func (m *BlockContents) XXX_Size() int {
	return xxx_messageInfo_BlockContents.Size(m)
}
func (m *BlockContents) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockContents.DiscardUnknown(m)
}

var xxx_messageInfo_BlockContents proto.InternalMessageInfo

func (m *BlockContents) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *BlockContents) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *BlockContents) GetPrevious() string {
	if m != nil {
		return m.Previous
	}
	return ""
}

func (m *BlockContents) GetRepresentative() string {
	if m != nil {
		return m.Representative
	}
	return ""
}

func (m *BlockContents) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *BlockContents) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *BlockContents) GetLinkAsAccount() string {
	if m != nil {
		return m.LinkAsAccount
	}
	return ""
}

func (m *BlockContents) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *BlockContents) GetWork() string {
	if m != nil {
		return m.Work
	}
	return ""
}

func (m *BlockContents) GetSubtype() string {
	if m != nil {
		return m.Subtype
	}
	return ""
}

type BlocksInfoRequest struct {
	Hashes               []string `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlocksInfoRequest) Reset()         { *m = BlocksInfoRequest{} }
func (m *BlocksInfoRequest) String() string { return proto.CompactTextString(m) }
func (*BlocksInfoRequest) ProtoMessage()    {}
func (*BlocksInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11bdccbcd58847bb, []int{14}
}

func (m *BlocksInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlocksInfoRequest.Unmarshal(m, b)
}
func (m *BlocksInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlocksInfoRequest.Marshal(b, m, deterministic)
}
func (m *BlocksInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlocksInfoRequest.Merge(m, src)
}
func (m *BlocksInfoRequest) XXX_Size() int {
	return xxx_messageInfo_BlocksInfoRequest.Size(m)
}
func (m *BlocksInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlocksInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlocksInfoRequest proto.InternalMessageInfo

func (m *BlocksInfoRequest) GetHashes() []string {
	if m != nil {
		return m.Hashes
	}
	return nil
}

type BlocksInfoReply struct {
	BlockHash            string          `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Block                *BlockInfoReply `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BlocksInfoReply) Reset()         { *m = BlocksInfoReply{} }
func (m *BlocksInfoReply) String() string { return proto.CompactTextString(m) }
func (*BlocksInfoReply) ProtoMessage()    {}
func (*BlocksInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_11bdccbcd58847bb, []int{15}
}

func (m *BlocksInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlocksInfoReply.Unmarshal(m, b)
}
func (m *BlocksInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlocksInfoReply.Marshal(b, m, deterministic)
}
func (m *BlocksInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlocksInfoReply.Merge(m, src)
}
func (m *BlocksInfoReply) XXX_Size() int {
	return xxx_messageInfo_BlocksInfoReply.Size(m)
}
func (m *BlocksInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BlocksInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_BlocksInfoReply proto.InternalMessageInfo

func (m *BlocksInfoReply) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *BlocksInfoReply) GetBlock() *BlockInfoReply {
	if m != nil {
		return m.Block
	}
	return nil
}

type SubscribeRequest struct {
	Accounts             []string `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11bdccbcd58847bb, []int{16}
}

func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(m, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

func (m *SubscribeRequest) GetAccounts() []string {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type ElectionInfo struct {
	Duration             string   `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration,omitempty"`
	Time                 string   `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Tally                string   `protobuf:"bytes,3,opt,name=tally,proto3" json:"tally,omitempty"`
	RequestCount         string   `protobuf:"bytes,4,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ElectionInfo) Reset()         { *m = ElectionInfo{} }
func (m *ElectionInfo) String() string { return proto.CompactTextString(m) }
func (*ElectionInfo) ProtoMessage()    {}
func (*ElectionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_11bdccbcd58847bb, []int{17}
}

func (m *ElectionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ElectionInfo.Unmarshal(m, b)
}
func (m *ElectionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ElectionInfo.Marshal(b, m, deterministic)
}
func (m *ElectionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ElectionInfo.Merge(m, src)
}
func (m *ElectionInfo) XXX_Size() int {
	return xxx_messageInfo_ElectionInfo.Size(m)
}
func (m *ElectionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ElectionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ElectionInfo proto.InternalMessageInfo

func (m *ElectionInfo) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

func (m *ElectionInfo) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *ElectionInfo) GetTally() string {
	if m != nil {
		return m.Tally
	}
	return ""
}

func (m *ElectionInfo) GetRequestCount() string {
	if m != nil {
		return m.RequestCount
	}
	return ""
}

type SubscriptionMessage struct {
	Account              string             `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Signature            string             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Sequence             string             `protobuf:"bytes,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Blocks               []string           `protobuf:"bytes,4,rep,name=blocks,proto3" json:"blocks,omitempty"`
	Amount               string             `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Hash                 string             `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
	ConfirmationType     string             `protobuf:"bytes,7,opt,name=confirmation_type,json=confirmationType,proto3" json:"confirmation_type,omitempty"`
	ElectionInfo         *ElectionInfo      `protobuf:"bytes,8,opt,name=election_info,json=electionInfo,proto3" json:"election_info,omitempty"`
	Block                *SubscriptionBlock `protobuf:"bytes,9,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SubscriptionMessage) Reset()         { *m = SubscriptionMessage{} }
func (m *SubscriptionMessage) String() string { return proto.CompactTextString(m) }
func (*SubscriptionMessage) ProtoMessage()    {}
func (*SubscriptionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_11bdccbcd58847bb, []int{18}
}

func (m *SubscriptionMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscriptionMessage.Unmarshal(m, b)
}
func (m *SubscriptionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscriptionMessage.Marshal(b, m, deterministic)
}
func (m *SubscriptionMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscriptionMessage.Merge(m, src)
}
func (m *SubscriptionMessage) XXX_Size() int {
	return xxx_messageInfo_SubscriptionMessage.Size(m)
}
func (m *SubscriptionMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscriptionMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SubscriptionMessage proto.InternalMessageInfo

func (m *SubscriptionMessage) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *SubscriptionMessage) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *SubscriptionMessage) GetSequence() string {
	if m != nil {
		return m.Sequence
	}
	return ""
}

func (m *SubscriptionMessage) GetBlocks() []string {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func (m *SubscriptionMessage) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *SubscriptionMessage) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *SubscriptionMessage) GetConfirmationType() string {
	if m != nil {
		return m.ConfirmationType
	}
	return ""
}

func (m *SubscriptionMessage) GetElectionInfo() *ElectionInfo {
	if m != nil {
		return m.ElectionInfo
	}
	return nil
}

func (m *SubscriptionMessage) GetBlock() *SubscriptionBlock {
	if m != nil {
		return m.Block
	}
	return nil
}

type SubscriptionBlock struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Representative       string   `protobuf:"bytes,3,opt,name=representative,proto3" json:"representative,omitempty"`
	Account              string   `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	Work                 string   `protobuf:"bytes,5,opt,name=work,proto3" json:"work,omitempty"`
	Signature            string   `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	Previous             string   `protobuf:"bytes,7,opt,name=previous,proto3" json:"previous,omitempty"`
	LinkAsAccount        string   `protobuf:"bytes,8,opt,name=link_as_account,json=linkAsAccount,proto3" json:"link_as_account,omitempty"`
	Subtype              string   `protobuf:"bytes,9,opt,name=subtype,proto3" json:"subtype,omitempty"`
	Link                 string   `protobuf:"bytes,10,opt,name=link,proto3" json:"link,omitempty"`
	Balance              string   `protobuf:"bytes,11,opt,name=balance,proto3" json:"balance,omitempty"`
	Destination          string   `protobuf:"bytes,12,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscriptionBlock) Reset()         { *m = SubscriptionBlock{} }
func (m *SubscriptionBlock) String() string { return proto.CompactTextString(m) }
func (*SubscriptionBlock) ProtoMessage()    {}
func (*SubscriptionBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_11bdccbcd58847bb, []int{19}
}

func (m *SubscriptionBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscriptionBlock.Unmarshal(m, b)
}
func (m *SubscriptionBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscriptionBlock.Marshal(b, m, deterministic)
}
func (m *SubscriptionBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscriptionBlock.Merge(m, src)
}
func (m *SubscriptionBlock) XXX_Size() int {
	return xxx_messageInfo_SubscriptionBlock.Size(m)
}
func (m *SubscriptionBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscriptionBlock.DiscardUnknown(m)
}

var xxx_messageInfo_SubscriptionBlock proto.InternalMessageInfo

func (m *SubscriptionBlock) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SubscriptionBlock) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *SubscriptionBlock) GetRepresentative() string {
	if m != nil {
		return m.Representative
	}
	return ""
}

func (m *SubscriptionBlock) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *SubscriptionBlock) GetWork() string {
	if m != nil {
		return m.Work
	}
	return ""
}

func (m *SubscriptionBlock) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *SubscriptionBlock) GetPrevious() string {
	if m != nil {
		return m.Previous
	}
	return ""
}

func (m *SubscriptionBlock) GetLinkAsAccount() string {
	if m != nil {
		return m.LinkAsAccount
	}
	return ""
}

func (m *SubscriptionBlock) GetSubtype() string {
	if m != nil {
		return m.Subtype
	}
	return ""
}

func (m *SubscriptionBlock) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *SubscriptionBlock) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *SubscriptionBlock) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

type SubscriptionEntry struct {
	Topic                string               `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Time                 string               `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Message              *SubscriptionMessage `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SubscriptionEntry) Reset()         { *m = SubscriptionEntry{} }
func (m *SubscriptionEntry) String() string { return proto.CompactTextString(m) }
func (*SubscriptionEntry) ProtoMessage()    {}
func (*SubscriptionEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_11bdccbcd58847bb, []int{20}
}

func (m *SubscriptionEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscriptionEntry.Unmarshal(m, b)
}
func (m *SubscriptionEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscriptionEntry.Marshal(b, m, deterministic)
}
func (m *SubscriptionEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscriptionEntry.Merge(m, src)
}
func (m *SubscriptionEntry) XXX_Size() int {
	return xxx_messageInfo_SubscriptionEntry.Size(m)
}
func (m *SubscriptionEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscriptionEntry.DiscardUnknown(m)
}

var xxx_messageInfo_SubscriptionEntry proto.InternalMessageInfo

func (m *SubscriptionEntry) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *SubscriptionEntry) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *SubscriptionEntry) GetMessage() *SubscriptionMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*SendRequest)(nil), "nanoproto.SendRequest")
	proto.RegisterType((*SendReply)(nil), "nanoproto.SendReply")
	proto.RegisterType((*ValidateAccountNumberRequest)(nil), "nanoproto.ValidateAccountNumberRequest")
	proto.RegisterType((*ValidateAccountNumberReply)(nil), "nanoproto.ValidateAccountNumberReply")
	proto.RegisterType((*AccountCreateRequest)(nil), "nanoproto.AccountCreateRequest")
	proto.RegisterType((*AccountCreateReply)(nil), "nanoproto.AccountCreateReply")
	proto.RegisterType((*AccountBalanceRequest)(nil), "nanoproto.AccountBalanceRequest")
	proto.RegisterType((*AccountBalanceReply)(nil), "nanoproto.AccountBalanceReply")
	proto.RegisterType((*AccountsBalancesRequest)(nil), "nanoproto.AccountsBalancesRequest")
	proto.RegisterType((*Balance)(nil), "nanoproto.Balance")
	proto.RegisterType((*AccountsBalancesReply)(nil), "nanoproto.AccountsBalancesReply")
	proto.RegisterMapType((map[string]*Balance)(nil), "nanoproto.AccountsBalancesReply.BalancesEntry")
	proto.RegisterType((*BlockInfoRequest)(nil), "nanoproto.BlockInfoRequest")
	proto.RegisterType((*BlockInfoReply)(nil), "nanoproto.BlockInfoReply")
	proto.RegisterType((*BlockContents)(nil), "nanoproto.BlockContents")
	proto.RegisterType((*BlocksInfoRequest)(nil), "nanoproto.BlocksInfoRequest")
	proto.RegisterType((*BlocksInfoReply)(nil), "nanoproto.BlocksInfoReply")
	proto.RegisterType((*SubscribeRequest)(nil), "nanoproto.SubscribeRequest")
	proto.RegisterType((*ElectionInfo)(nil), "nanoproto.ElectionInfo")
	proto.RegisterType((*SubscriptionMessage)(nil), "nanoproto.SubscriptionMessage")
	proto.RegisterType((*SubscriptionBlock)(nil), "nanoproto.SubscriptionBlock")
	proto.RegisterType((*SubscriptionEntry)(nil), "nanoproto.SubscriptionEntry")
}

func init() { proto.RegisterFile("nano.proto", fileDescriptor_11bdccbcd58847bb) }

var fileDescriptor_11bdccbcd58847bb = []byte{
	// 1138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xde, 0x38, 0xbf, 0x3e, 0x69, 0xda, 0x74, 0xb6, 0xdb, 0x35, 0xde, 0xec, 0x52, 0x8c, 0xe8,
	0x56, 0x5a, 0xc9, 0x40, 0x80, 0x55, 0x85, 0xe0, 0x62, 0x53, 0x55, 0xea, 0x56, 0xb0, 0x2c, 0xd9,
	0x8a, 0x95, 0xb8, 0x89, 0x26, 0xce, 0x34, 0xb1, 0xea, 0xd8, 0xc6, 0x63, 0x37, 0xe4, 0x21, 0xb8,
	0xe5, 0x01, 0xe0, 0x15, 0x78, 0x0c, 0x5e, 0x82, 0x37, 0x41, 0xf3, 0xe7, 0x8c, 0x93, 0xb8, 0x85,
	0xab, 0xce, 0x39, 0x73, 0x7e, 0xc6, 0xdf, 0x39, 0xe7, 0xcb, 0x29, 0x40, 0x88, 0xc3, 0xc8, 0x8d,
	0x93, 0x28, 0x8d, 0x90, 0xc9, 0xce, 0xfc, 0xe8, 0x2c, 0xa0, 0xfd, 0x8e, 0x84, 0x93, 0x21, 0xf9,
	0x25, 0x23, 0x34, 0x45, 0x87, 0xd0, 0x58, 0xe0, 0x20, 0x20, 0xa9, 0x55, 0x39, 0xaa, 0x9c, 0x98,
	0x43, 0x29, 0x31, 0x3d, 0x8d, 0xb2, 0xc4, 0x23, 0x96, 0x21, 0xf4, 0x42, 0x42, 0x47, 0xd0, 0x9e,
	0x10, 0x9a, 0xfa, 0x21, 0x4e, 0xfd, 0x28, 0xb4, 0xaa, 0xfc, 0x52, 0x57, 0x31, 0x4f, 0x3c, 0x8f,
	0xb2, 0x30, 0xb5, 0x6a, 0xc2, 0x53, 0x48, 0xce, 0x47, 0x60, 0x8a, 0xc4, 0x71, 0xb0, 0x44, 0x07,
	0x50, 0x1f, 0x07, 0x91, 0x77, 0x23, 0xb3, 0x0a, 0xc1, 0x39, 0x85, 0xde, 0x4f, 0x38, 0xf0, 0x27,
	0x38, 0x25, 0xaf, 0x3c, 0x8f, 0x79, 0xbd, 0xc9, 0xe6, 0x63, 0x92, 0xa8, 0xc7, 0x5a, 0xd0, 0xc4,
	0x42, 0x2f, 0xfd, 0x94, 0xe8, 0xf4, 0xc1, 0x2e, 0xf1, 0x94, 0xd9, 0x6e, 0xd9, 0xad, 0xca, 0xc6,
	0x05, 0xc7, 0x85, 0x03, 0x69, 0x7b, 0x96, 0x10, 0x9c, 0x92, 0x7b, 0x20, 0x71, 0x5c, 0x40, 0x6b,
	0xf6, 0x2c, 0x76, 0xf9, 0x9b, 0x3e, 0x87, 0x47, 0xd2, 0x7e, 0x80, 0x03, 0x1c, 0x7a, 0xe4, 0xfe,
	0xcf, 0x78, 0x0d, 0x0f, 0xd7, 0x5d, 0x64, 0x8e, 0xb1, 0x90, 0x95, 0x83, 0x14, 0xd9, 0x4d, 0x4c,
	0xc2, 0x89, 0x1f, 0x4e, 0x65, 0x9d, 0x94, 0xe8, 0x7c, 0x05, 0x8f, 0x65, 0x28, 0x2a, 0x63, 0x51,
	0x95, 0xdf, 0x86, 0x96, 0x4c, 0x48, 0xad, 0xca, 0x51, 0xf5, 0xc4, 0x1c, 0xe6, 0xb2, 0xf3, 0x2d,
	0x34, 0x07, 0xab, 0xd8, 0xff, 0x3b, 0xeb, 0x5f, 0x95, 0xfc, 0xa3, 0xb5, 0xb4, 0xec, 0x1b, 0x2e,
	0xa1, 0x25, 0xdd, 0x45, 0xd2, 0x76, 0xdf, 0x75, 0xf3, 0xae, 0x74, 0xb7, 0xfa, 0xb8, 0x4a, 0x3a,
	0x0f, 0xd3, 0x64, 0x39, 0xcc, 0xfd, 0xed, 0x1f, 0xa0, 0x53, 0xb8, 0x42, 0x5d, 0xa8, 0xde, 0x90,
	0xa5, 0x7c, 0x26, 0x3b, 0xa2, 0x13, 0x5e, 0xf2, 0x4c, 0xb4, 0x6f, 0xbb, 0x8f, 0xb4, 0x5c, 0x0a,
	0x5a, 0x61, 0xf0, 0xb5, 0x71, 0x5a, 0x71, 0x8e, 0xa1, 0x3b, 0x60, 0x1d, 0xf8, 0x3a, 0xbc, 0x8e,
	0x14, 0x4a, 0x08, 0x6a, 0x33, 0x4c, 0x67, 0x32, 0x28, 0x3f, 0x3b, 0xbf, 0x1b, 0xb0, 0xab, 0x19,
	0xb2, 0xef, 0xfa, 0x18, 0x3a, 0xbc, 0x79, 0x47, 0xc5, 0x92, 0xee, 0x70, 0xa5, 0xfc, 0x2c, 0x6d,
	0x26, 0x0c, 0x7d, 0x26, 0x74, 0x88, 0xab, 0x45, 0x88, 0x0f, 0xa1, 0x31, 0x23, 0xfe, 0x74, 0x96,
	0x4f, 0x91, 0x90, 0xd0, 0x73, 0xd8, 0x0b, 0x22, 0x0f, 0x07, 0xa3, 0xd4, 0x9f, 0x13, 0x9a, 0xe2,
	0x79, 0x6c, 0xd5, 0xb9, 0xc1, 0x2e, 0x57, 0x5f, 0x29, 0x2d, 0xea, 0x81, 0xe9, 0x45, 0xe1, 0xb5,
	0x9f, 0xcc, 0xc9, 0xc4, 0x6a, 0x70, 0x93, 0x95, 0x02, 0x7d, 0x09, 0x2d, 0x2f, 0x0a, 0x53, 0xc2,
	0x5a, 0xa0, 0xc9, 0x11, 0xb2, 0x74, 0x84, 0xd8, 0xdb, 0xcf, 0xe4, 0xfd, 0x30, 0xb7, 0x64, 0xcf,
	0xa5, 0xd9, 0x38, 0x5d, 0xc6, 0xc4, 0x6a, 0x89, 0xe7, 0x4a, 0xd1, 0xf9, 0xd3, 0x80, 0x4e, 0xc1,
	0x8b, 0xc1, 0xc7, 0x0d, 0x25, 0x7c, 0xec, 0xac, 0x37, 0xbe, 0x51, 0x68, 0x7c, 0xd6, 0x92, 0x71,
	0x42, 0x6e, 0xfd, 0x28, 0xa3, 0x12, 0x89, 0x5c, 0x46, 0xc7, 0xb0, 0x9b, 0x90, 0x38, 0x21, 0x94,
	0x84, 0x29, 0x4e, 0xfd, 0x5b, 0x22, 0x21, 0x59, 0xd3, 0xea, 0x60, 0xd6, 0x8b, 0x60, 0x22, 0xa8,
	0x05, 0x7e, 0x78, 0x23, 0x61, 0xe0, 0x67, 0x74, 0x0c, 0x7b, 0xec, 0xef, 0x08, 0xd3, 0xbc, 0x72,
	0x4d, 0x7e, 0xdd, 0x61, 0xea, 0x57, 0x54, 0x95, 0xae, 0x07, 0x26, 0xf5, 0xa7, 0x21, 0x4e, 0xb3,
	0x44, 0x7d, 0xf5, 0x4a, 0xc1, 0x22, 0x2f, 0xa2, 0xe4, 0xc6, 0x32, 0x45, 0x64, 0x76, 0xd6, 0x51,
	0x82, 0x22, 0x4a, 0x2f, 0x60, 0x9f, 0x83, 0x44, 0xf5, 0x3e, 0x63, 0x95, 0xc6, 0x74, 0x46, 0xd4,
	0x2c, 0x4a, 0xc9, 0xc1, 0xb0, 0xa7, 0x1b, 0xb3, 0x5e, 0x7b, 0x0a, 0x20, 0x7a, 0x4d, 0x6b, 0x4c,
	0x93, 0x6b, 0x2e, 0x30, 0x9d, 0xa1, 0x4f, 0x15, 0xa9, 0x8a, 0x9e, 0xff, 0x60, 0xbd, 0xa2, 0x79,
	0x20, 0xc5, 0xb7, 0x2e, 0x74, 0xdf, 0x65, 0x63, 0xea, 0x25, 0xfe, 0x98, 0xfc, 0x17, 0x72, 0x58,
	0xc2, 0xce, 0x79, 0x40, 0x3c, 0x46, 0xf3, 0x2c, 0x16, 0xb3, 0x9d, 0x64, 0x89, 0xf8, 0x25, 0x10,
	0xaf, 0xc9, 0x65, 0x5e, 0x7f, 0x7f, 0xae, 0x7e, 0x3e, 0xf8, 0x99, 0xf1, 0x70, 0x8a, 0x83, 0x60,
	0x29, 0x4b, 0x2c, 0x04, 0x36, 0x41, 0x89, 0x48, 0x3e, 0xf2, 0xb4, 0xdf, 0x8d, 0x1d, 0xa9, 0x3c,
	0xe3, 0xcc, 0xf8, 0xb7, 0x01, 0x0f, 0xe5, 0x5b, 0x63, 0x16, 0xff, 0x7b, 0x42, 0x29, 0x9e, 0x92,
	0x72, 0x2e, 0x2d, 0x16, 0xce, 0x58, 0x2f, 0x9c, 0x0d, 0x2d, 0xca, 0xe2, 0xaf, 0x46, 0x2f, 0x97,
	0x59, 0x45, 0x38, 0x3e, 0xd4, 0xaa, 0x89, 0x8a, 0x08, 0x49, 0x9b, 0xe2, 0x7a, 0x61, 0x8a, 0x15,
	0x53, 0x34, 0x56, 0x4c, 0x81, 0x5e, 0xc0, 0xbe, 0x9c, 0x36, 0x0e, 0xc7, 0x88, 0xb7, 0x83, 0x68,
	0xb0, 0xae, 0x7e, 0x71, 0xc5, 0xe6, 0xe2, 0x1b, 0xe8, 0x10, 0x89, 0xeb, 0xc8, 0x0f, 0xaf, 0x23,
	0xde, 0x67, 0xed, 0xfe, 0x63, 0xad, 0x80, 0x3a, 0xee, 0xc3, 0x1d, 0xa2, 0x57, 0xa1, 0xaf, 0xca,
	0x6e, 0x72, 0xaf, 0x9e, 0xe6, 0xa5, 0x23, 0xc6, 0x5b, 0x40, 0x55, 0xfe, 0x1f, 0x03, 0xf6, 0x37,
	0x2e, 0xb7, 0xce, 0x6c, 0xd9, 0x22, 0xb0, 0x39, 0x95, 0xd5, 0xb2, 0xa9, 0x54, 0x05, 0xaa, 0x15,
	0x0b, 0xa4, 0x66, 0xa7, 0xae, 0xcd, 0x4e, 0xa1, 0x68, 0x8d, 0x2d, 0x45, 0xcb, 0x59, 0xa2, 0xb9,
	0xc1, 0x12, 0x1b, 0xf3, 0xdc, 0xda, 0x36, 0xcf, 0xda, 0x74, 0x9a, 0x85, 0xe9, 0xcc, 0x59, 0x02,
	0x34, 0x96, 0xd0, 0x38, 0xa5, 0x5d, 0xe4, 0x94, 0xb5, 0x45, 0x68, 0x67, 0x63, 0x11, 0x72, 0x16,
	0x45, 0x88, 0xc5, 0x2f, 0x15, 0x1b, 0x81, 0x28, 0xf6, 0x3d, 0xb5, 0x8a, 0x70, 0x61, 0xeb, 0xb0,
	0x9c, 0x42, 0x73, 0x2e, 0x9a, 0x9c, 0x23, 0xdb, 0xee, 0x3f, 0x2b, 0x29, 0xac, 0x1c, 0x85, 0xa1,
	0x32, 0xef, 0xff, 0x56, 0x87, 0xda, 0x1b, 0x1c, 0x46, 0xe8, 0x12, 0x60, 0x45, 0x21, 0xa8, 0xb7,
	0xce, 0x07, 0x3a, 0x0d, 0xd9, 0x76, 0xc9, 0x6d, 0x1c, 0x2c, 0x9d, 0x07, 0x9f, 0x55, 0xd0, 0x39,
	0x98, 0x39, 0x89, 0xa0, 0x27, 0xdb, 0xa9, 0x45, 0x44, 0x2a, 0xe7, 0x1d, 0xe7, 0x01, 0xba, 0x04,
	0x33, 0xa7, 0x9c, 0x42, 0x98, 0x75, 0x22, 0xb2, 0xcb, 0xfa, 0x98, 0xe3, 0xc8, 0x9f, 0xf4, 0x33,
	0x74, 0xd7, 0xf7, 0x06, 0xe4, 0xdc, 0xb9, 0x54, 0x88, 0xc8, 0x47, 0xf7, 0x2d, 0x1e, 0xce, 0x03,
	0x74, 0x05, 0xbb, 0xc5, 0x4d, 0x0c, 0x6d, 0xf1, 0x2a, 0xee, 0x75, 0xf6, 0xb3, 0x3b, 0x2c, 0x44,
	0xd4, 0x1f, 0xa1, 0x53, 0x58, 0x21, 0xd1, 0x87, 0x9b, 0x2e, 0x85, 0x65, 0xd4, 0x7e, 0x5a, 0x6e,
	0x20, 0x42, 0xfa, 0xf0, 0x68, 0xeb, 0xe6, 0x8b, 0x9e, 0x6b, 0x9e, 0x77, 0x6d, 0xd5, 0xf6, 0x27,
	0xf7, 0x1b, 0x8a, 0x54, 0x2f, 0xa1, 0xc6, 0x36, 0x78, 0x74, 0xa8, 0x57, 0x66, 0xf5, 0xbf, 0x84,
	0x7d, 0xb0, 0xa1, 0xe7, 0x7e, 0x83, 0x97, 0xf0, 0xc4, 0x8f, 0xdc, 0x69, 0x12, 0x7b, 0x2e, 0xf9,
	0x15, 0xcf, 0xe3, 0x80, 0x50, 0x77, 0x46, 0x82, 0x20, 0x5a, 0x44, 0x49, 0x30, 0x19, 0xec, 0x5d,
	0xb0, 0xf3, 0x7b, 0x76, 0x7e, 0xcb, 0x7c, 0xdf, 0x56, 0xfe, 0x30, 0xaa, 0x17, 0xdf, 0xbd, 0x1f,
	0x37, 0x78, 0xa8, 0x2f, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x27, 0x4a, 0x76, 0x6d, 0xca, 0x0c,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NanoClient is the client API for Nano service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NanoClient interface {
	BlocksInfo(ctx context.Context, in *BlocksInfoRequest, opts ...grpc.CallOption) (Nano_BlocksInfoClient, error)
	BlockInfo(ctx context.Context, in *BlockInfoRequest, opts ...grpc.CallOption) (*BlockInfoReply, error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (Nano_SubscribeClient, error)
	AccountsBalances(ctx context.Context, in *AccountsBalancesRequest, opts ...grpc.CallOption) (*AccountsBalancesReply, error)
	AccountBalance(ctx context.Context, in *AccountBalanceRequest, opts ...grpc.CallOption) (*AccountBalanceReply, error)
	AccountCreate(ctx context.Context, in *AccountCreateRequest, opts ...grpc.CallOption) (*AccountCreateReply, error)
	ValidateAccountNumber(ctx context.Context, in *ValidateAccountNumberRequest, opts ...grpc.CallOption) (*ValidateAccountNumberReply, error)
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendReply, error)
}

type nanoClient struct {
	cc *grpc.ClientConn
}

func NewNanoClient(cc *grpc.ClientConn) NanoClient {
	return &nanoClient{cc}
}

func (c *nanoClient) BlocksInfo(ctx context.Context, in *BlocksInfoRequest, opts ...grpc.CallOption) (Nano_BlocksInfoClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Nano_serviceDesc.Streams[0], "/nanoproto.Nano/BlocksInfo", opts...)
	if err != nil {
		return nil, err
	}
	x := &nanoBlocksInfoClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Nano_BlocksInfoClient interface {
	Recv() (*BlocksInfoReply, error)
	grpc.ClientStream
}

type nanoBlocksInfoClient struct {
	grpc.ClientStream
}

func (x *nanoBlocksInfoClient) Recv() (*BlocksInfoReply, error) {
	m := new(BlocksInfoReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nanoClient) BlockInfo(ctx context.Context, in *BlockInfoRequest, opts ...grpc.CallOption) (*BlockInfoReply, error) {
	out := new(BlockInfoReply)
	err := c.cc.Invoke(ctx, "/nanoproto.Nano/BlockInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nanoClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (Nano_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Nano_serviceDesc.Streams[1], "/nanoproto.Nano/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &nanoSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Nano_SubscribeClient interface {
	Recv() (*SubscriptionEntry, error)
	grpc.ClientStream
}

type nanoSubscribeClient struct {
	grpc.ClientStream
}

func (x *nanoSubscribeClient) Recv() (*SubscriptionEntry, error) {
	m := new(SubscriptionEntry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nanoClient) AccountsBalances(ctx context.Context, in *AccountsBalancesRequest, opts ...grpc.CallOption) (*AccountsBalancesReply, error) {
	out := new(AccountsBalancesReply)
	err := c.cc.Invoke(ctx, "/nanoproto.Nano/AccountsBalances", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nanoClient) AccountBalance(ctx context.Context, in *AccountBalanceRequest, opts ...grpc.CallOption) (*AccountBalanceReply, error) {
	out := new(AccountBalanceReply)
	err := c.cc.Invoke(ctx, "/nanoproto.Nano/AccountBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nanoClient) AccountCreate(ctx context.Context, in *AccountCreateRequest, opts ...grpc.CallOption) (*AccountCreateReply, error) {
	out := new(AccountCreateReply)
	err := c.cc.Invoke(ctx, "/nanoproto.Nano/AccountCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nanoClient) ValidateAccountNumber(ctx context.Context, in *ValidateAccountNumberRequest, opts ...grpc.CallOption) (*ValidateAccountNumberReply, error) {
	out := new(ValidateAccountNumberReply)
	err := c.cc.Invoke(ctx, "/nanoproto.Nano/ValidateAccountNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nanoClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendReply, error) {
	out := new(SendReply)
	err := c.cc.Invoke(ctx, "/nanoproto.Nano/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NanoServer is the server API for Nano service.
type NanoServer interface {
	BlocksInfo(*BlocksInfoRequest, Nano_BlocksInfoServer) error
	BlockInfo(context.Context, *BlockInfoRequest) (*BlockInfoReply, error)
	Subscribe(*SubscribeRequest, Nano_SubscribeServer) error
	AccountsBalances(context.Context, *AccountsBalancesRequest) (*AccountsBalancesReply, error)
	AccountBalance(context.Context, *AccountBalanceRequest) (*AccountBalanceReply, error)
	AccountCreate(context.Context, *AccountCreateRequest) (*AccountCreateReply, error)
	ValidateAccountNumber(context.Context, *ValidateAccountNumberRequest) (*ValidateAccountNumberReply, error)
	Send(context.Context, *SendRequest) (*SendReply, error)
}

// UnimplementedNanoServer can be embedded to have forward compatible implementations.
type UnimplementedNanoServer struct {
}

func (*UnimplementedNanoServer) BlocksInfo(req *BlocksInfoRequest, srv Nano_BlocksInfoServer) error {
	return status.Errorf(codes.Unimplemented, "method BlocksInfo not implemented")
}
func (*UnimplementedNanoServer) BlockInfo(ctx context.Context, req *BlockInfoRequest) (*BlockInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlockInfo not implemented")
}
func (*UnimplementedNanoServer) Subscribe(req *SubscribeRequest, srv Nano_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (*UnimplementedNanoServer) AccountsBalances(ctx context.Context, req *AccountsBalancesRequest) (*AccountsBalancesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountsBalances not implemented")
}
func (*UnimplementedNanoServer) AccountBalance(ctx context.Context, req *AccountBalanceRequest) (*AccountBalanceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountBalance not implemented")
}
func (*UnimplementedNanoServer) AccountCreate(ctx context.Context, req *AccountCreateRequest) (*AccountCreateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountCreate not implemented")
}
func (*UnimplementedNanoServer) ValidateAccountNumber(ctx context.Context, req *ValidateAccountNumberRequest) (*ValidateAccountNumberReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateAccountNumber not implemented")
}
func (*UnimplementedNanoServer) Send(ctx context.Context, req *SendRequest) (*SendReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}

func RegisterNanoServer(s *grpc.Server, srv NanoServer) {
	s.RegisterService(&_Nano_serviceDesc, srv)
}

func _Nano_BlocksInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BlocksInfoRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NanoServer).BlocksInfo(m, &nanoBlocksInfoServer{stream})
}

type Nano_BlocksInfoServer interface {
	Send(*BlocksInfoReply) error
	grpc.ServerStream
}

type nanoBlocksInfoServer struct {
	grpc.ServerStream
}

func (x *nanoBlocksInfoServer) Send(m *BlocksInfoReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Nano_BlockInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NanoServer).BlockInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nanoproto.Nano/BlockInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NanoServer).BlockInfo(ctx, req.(*BlockInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nano_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NanoServer).Subscribe(m, &nanoSubscribeServer{stream})
}

type Nano_SubscribeServer interface {
	Send(*SubscriptionEntry) error
	grpc.ServerStream
}

type nanoSubscribeServer struct {
	grpc.ServerStream
}

func (x *nanoSubscribeServer) Send(m *SubscriptionEntry) error {
	return x.ServerStream.SendMsg(m)
}

func _Nano_AccountsBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountsBalancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NanoServer).AccountsBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nanoproto.Nano/AccountsBalances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NanoServer).AccountsBalances(ctx, req.(*AccountsBalancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nano_AccountBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NanoServer).AccountBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nanoproto.Nano/AccountBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NanoServer).AccountBalance(ctx, req.(*AccountBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nano_AccountCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NanoServer).AccountCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nanoproto.Nano/AccountCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NanoServer).AccountCreate(ctx, req.(*AccountCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nano_ValidateAccountNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateAccountNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NanoServer).ValidateAccountNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nanoproto.Nano/ValidateAccountNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NanoServer).ValidateAccountNumber(ctx, req.(*ValidateAccountNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nano_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NanoServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nanoproto.Nano/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NanoServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Nano_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nanoproto.Nano",
	HandlerType: (*NanoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BlockInfo",
			Handler:    _Nano_BlockInfo_Handler,
		},
		{
			MethodName: "AccountsBalances",
			Handler:    _Nano_AccountsBalances_Handler,
		},
		{
			MethodName: "AccountBalance",
			Handler:    _Nano_AccountBalance_Handler,
		},
		{
			MethodName: "AccountCreate",
			Handler:    _Nano_AccountCreate_Handler,
		},
		{
			MethodName: "ValidateAccountNumber",
			Handler:    _Nano_ValidateAccountNumber_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _Nano_Send_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BlocksInfo",
			Handler:       _Nano_BlocksInfo_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _Nano_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nano.proto",
}
