// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nanoproto.proto

package nanoproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlocksInfoRequest struct {
	Hashes               []string `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlocksInfoRequest) Reset()         { *m = BlocksInfoRequest{} }
func (m *BlocksInfoRequest) String() string { return proto.CompactTextString(m) }
func (*BlocksInfoRequest) ProtoMessage()    {}
func (*BlocksInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_206b865a5f79aade, []int{0}
}

func (m *BlocksInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlocksInfoRequest.Unmarshal(m, b)
}
func (m *BlocksInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlocksInfoRequest.Marshal(b, m, deterministic)
}
func (m *BlocksInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlocksInfoRequest.Merge(m, src)
}
func (m *BlocksInfoRequest) XXX_Size() int {
	return xxx_messageInfo_BlocksInfoRequest.Size(m)
}
func (m *BlocksInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlocksInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlocksInfoRequest proto.InternalMessageInfo

func (m *BlocksInfoRequest) GetHashes() []string {
	if m != nil {
		return m.Hashes
	}
	return nil
}

type Block struct {
	BlockAccount         string         `protobuf:"bytes,1,opt,name=block_account,json=blockAccount,proto3" json:"block_account,omitempty"`
	Amount               string         `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Balance              string         `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Height               string         `protobuf:"bytes,4,opt,name=height,proto3" json:"height,omitempty"`
	LocalTimestamp       string         `protobuf:"bytes,5,opt,name=local_timestamp,json=localTimestamp,proto3" json:"local_timestamp,omitempty"`
	Confirmed            string         `protobuf:"bytes,6,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	Contents             *BlockContents `protobuf:"bytes,7,opt,name=contents,proto3" json:"contents,omitempty"`
	Subtype              string         `protobuf:"bytes,8,opt,name=subtype,proto3" json:"subtype,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_206b865a5f79aade, []int{1}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetBlockAccount() string {
	if m != nil {
		return m.BlockAccount
	}
	return ""
}

func (m *Block) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Block) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *Block) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

func (m *Block) GetLocalTimestamp() string {
	if m != nil {
		return m.LocalTimestamp
	}
	return ""
}

func (m *Block) GetConfirmed() string {
	if m != nil {
		return m.Confirmed
	}
	return ""
}

func (m *Block) GetContents() *BlockContents {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *Block) GetSubtype() string {
	if m != nil {
		return m.Subtype
	}
	return ""
}

type BlockContents struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Previous             string   `protobuf:"bytes,3,opt,name=previous,proto3" json:"previous,omitempty"`
	Representative       string   `protobuf:"bytes,4,opt,name=representative,proto3" json:"representative,omitempty"`
	Balance              string   `protobuf:"bytes,5,opt,name=balance,proto3" json:"balance,omitempty"`
	Link                 string   `protobuf:"bytes,6,opt,name=link,proto3" json:"link,omitempty"`
	LinkAsAccount        string   `protobuf:"bytes,7,opt,name=link_as_account,json=linkAsAccount,proto3" json:"link_as_account,omitempty"`
	Signature            string   `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	Work                 string   `protobuf:"bytes,9,opt,name=work,proto3" json:"work,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockContents) Reset()         { *m = BlockContents{} }
func (m *BlockContents) String() string { return proto.CompactTextString(m) }
func (*BlockContents) ProtoMessage()    {}
func (*BlockContents) Descriptor() ([]byte, []int) {
	return fileDescriptor_206b865a5f79aade, []int{2}
}

func (m *BlockContents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockContents.Unmarshal(m, b)
}
func (m *BlockContents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockContents.Marshal(b, m, deterministic)
}
func (m *BlockContents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockContents.Merge(m, src)
}
func (m *BlockContents) XXX_Size() int {
	return xxx_messageInfo_BlockContents.Size(m)
}
func (m *BlockContents) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockContents.DiscardUnknown(m)
}

var xxx_messageInfo_BlockContents proto.InternalMessageInfo

func (m *BlockContents) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *BlockContents) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *BlockContents) GetPrevious() string {
	if m != nil {
		return m.Previous
	}
	return ""
}

func (m *BlockContents) GetRepresentative() string {
	if m != nil {
		return m.Representative
	}
	return ""
}

func (m *BlockContents) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *BlockContents) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *BlockContents) GetLinkAsAccount() string {
	if m != nil {
		return m.LinkAsAccount
	}
	return ""
}

func (m *BlockContents) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *BlockContents) GetWork() string {
	if m != nil {
		return m.Work
	}
	return ""
}

type BlocksInfoReply struct {
	Blocks               map[string]*Block `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BlocksInfoReply) Reset()         { *m = BlocksInfoReply{} }
func (m *BlocksInfoReply) String() string { return proto.CompactTextString(m) }
func (*BlocksInfoReply) ProtoMessage()    {}
func (*BlocksInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_206b865a5f79aade, []int{3}
}

func (m *BlocksInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlocksInfoReply.Unmarshal(m, b)
}
func (m *BlocksInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlocksInfoReply.Marshal(b, m, deterministic)
}
func (m *BlocksInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlocksInfoReply.Merge(m, src)
}
func (m *BlocksInfoReply) XXX_Size() int {
	return xxx_messageInfo_BlocksInfoReply.Size(m)
}
func (m *BlocksInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BlocksInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_BlocksInfoReply proto.InternalMessageInfo

func (m *BlocksInfoReply) GetBlocks() map[string]*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func init() {
	proto.RegisterType((*BlocksInfoRequest)(nil), "nanoproto.BlocksInfoRequest")
	proto.RegisterType((*Block)(nil), "nanoproto.Block")
	proto.RegisterType((*BlockContents)(nil), "nanoproto.BlockContents")
	proto.RegisterType((*BlocksInfoReply)(nil), "nanoproto.BlocksInfoReply")
	proto.RegisterMapType((map[string]*Block)(nil), "nanoproto.BlocksInfoReply.BlocksEntry")
}

func init() { proto.RegisterFile("nanoproto.proto", fileDescriptor_206b865a5f79aade) }

var fileDescriptor_206b865a5f79aade = []byte{
	// 496 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xcb, 0x8a, 0xdb, 0x30,
	0x14, 0xad, 0x9d, 0xc7, 0xc4, 0x37, 0xcd, 0x78, 0xaa, 0x45, 0x11, 0x69, 0x16, 0xc1, 0x85, 0x34,
	0x50, 0xf0, 0x22, 0x2d, 0xa5, 0x74, 0x51, 0x98, 0x94, 0x42, 0x4a, 0x4b, 0x09, 0xa6, 0x30, 0xcb,
	0xa0, 0x78, 0x34, 0x89, 0x89, 0x2c, 0xb9, 0x92, 0x9c, 0x69, 0x3e, 0xa1, 0x8b, 0xfe, 0x42, 0x17,
	0xfd, 0xd2, 0x22, 0x59, 0x8e, 0x33, 0x81, 0xd9, 0x24, 0xe7, 0x9c, 0xfb, 0xd0, 0xd5, 0xd1, 0x35,
	0x84, 0x9c, 0x70, 0x51, 0x48, 0xa1, 0x45, 0x6c, 0x7f, 0x51, 0x70, 0x14, 0xa2, 0xd7, 0xf0, 0x6c,
	0xce, 0x44, 0xba, 0x53, 0x5f, 0xf8, 0x9d, 0x48, 0xe8, 0xcf, 0x92, 0x2a, 0x8d, 0x9e, 0x43, 0x77,
	0x4b, 0xd4, 0x96, 0x2a, 0xec, 0x8d, 0x5b, 0xd3, 0x20, 0x71, 0x2c, 0xfa, 0xe3, 0x43, 0xc7, 0x66,
	0xa3, 0x97, 0x30, 0x58, 0x1b, 0xb0, 0x22, 0x69, 0x2a, 0x4a, 0xae, 0xb1, 0x37, 0xf6, 0xa6, 0x41,
	0xf2, 0xd4, 0x8a, 0xd7, 0x95, 0x66, 0xda, 0x90, 0xdc, 0x46, 0x7d, 0x1b, 0x75, 0x0c, 0x61, 0xb8,
	0x58, 0x13, 0x46, 0x78, 0x4a, 0x71, 0xcb, 0x06, 0x6a, 0x6a, 0x0f, 0xa6, 0xd9, 0x66, 0xab, 0x71,
	0xbb, 0xaa, 0xa8, 0x18, 0x7a, 0x05, 0x21, 0x13, 0x29, 0x61, 0x2b, 0x9d, 0xe5, 0x54, 0x69, 0x92,
	0x17, 0xb8, 0x63, 0x13, 0x2e, 0xad, 0xfc, 0xa3, 0x56, 0xd1, 0x08, 0x82, 0x54, 0xf0, 0xbb, 0x4c,
	0xe6, 0xf4, 0x16, 0x77, 0x6d, 0x4a, 0x23, 0xa0, 0xb7, 0xd0, 0x4b, 0x05, 0xd7, 0x94, 0x6b, 0x85,
	0x2f, 0xc6, 0xde, 0xb4, 0x3f, 0xc3, 0x71, 0xe3, 0x8d, 0xbd, 0xd9, 0x27, 0x17, 0x4f, 0x8e, 0x99,
	0x66, 0x5c, 0x55, 0xae, 0xf5, 0xa1, 0xa0, 0xb8, 0x57, 0x8d, 0xeb, 0x68, 0xf4, 0xdb, 0x87, 0xc1,
	0x83, 0x2a, 0x84, 0xa0, 0x6d, 0x13, 0x2b, 0x3b, 0x2c, 0x36, 0xf5, 0xb5, 0x4b, 0x95, 0x0f, 0x35,
	0x45, 0x43, 0xe8, 0x15, 0x92, 0xee, 0x33, 0x51, 0x2a, 0xe7, 0xc4, 0x91, 0xa3, 0x09, 0x5c, 0x4a,
	0x5a, 0x48, 0xaa, 0x28, 0xd7, 0x44, 0x67, 0x7b, 0xea, 0x2c, 0x39, 0x53, 0x4f, 0xcd, 0xec, 0x3c,
	0x34, 0x13, 0x41, 0x9b, 0x65, 0x7c, 0xe7, 0x6c, 0xb0, 0x18, 0x4d, 0x20, 0x34, 0xff, 0x2b, 0xa2,
	0x8e, 0x2f, 0x77, 0x61, 0xc3, 0x03, 0x23, 0x5f, 0xab, 0xfa, 0xe9, 0x46, 0x10, 0xa8, 0x6c, 0xc3,
	0x89, 0x2e, 0x65, 0x7d, 0xeb, 0x46, 0x30, 0x9d, 0xef, 0x85, 0xdc, 0xe1, 0xa0, 0xea, 0x6c, 0x70,
	0xf4, 0xd7, 0x83, 0xf0, 0x74, 0x93, 0x0a, 0x76, 0x40, 0x1f, 0xa1, 0x6b, 0x17, 0xa2, 0xda, 0xa3,
	0xfe, 0x6c, 0x72, 0xee, 0x76, 0x93, 0xeb, 0xf8, 0x67, 0xae, 0xe5, 0x21, 0x71, 0x55, 0xc3, 0xaf,
	0xd0, 0x3f, 0x91, 0xd1, 0x15, 0xb4, 0x76, 0xf4, 0xe0, 0xbc, 0x35, 0x10, 0x4d, 0xa0, 0xb3, 0x27,
	0xac, 0xa4, 0xd6, 0xd8, 0xfe, 0xec, 0xea, 0xbc, 0x7f, 0x52, 0x85, 0x3f, 0xf8, 0xef, 0xbd, 0xd9,
	0x12, 0xda, 0xdf, 0x09, 0x17, 0x68, 0x01, 0xd0, 0x9c, 0x8d, 0x46, 0x8f, 0x8c, 0x64, 0x3f, 0x84,
	0xe1, 0xf0, 0xf1, 0x81, 0xa3, 0x27, 0xf3, 0x77, 0xf0, 0x22, 0x13, 0xf1, 0x46, 0x16, 0x69, 0x4c,
	0x7f, 0x91, 0xbc, 0x60, 0x54, 0xc5, 0x5b, 0xca, 0x98, 0xb8, 0x17, 0x92, 0xdd, 0xce, 0xc3, 0x85,
	0xc1, 0x37, 0x06, 0x2f, 0x4d, 0x87, 0xa5, 0xf7, 0xcf, 0x6f, 0x2d, 0xbe, 0xdd, 0xac, 0xbb, 0xb6,
	0xe1, 0x9b, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0e, 0xab, 0xf5, 0x64, 0x98, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NanoClient is the client API for Nano service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NanoClient interface {
	BlocksInfo(ctx context.Context, in *BlocksInfoRequest, opts ...grpc.CallOption) (*BlocksInfoReply, error)
}

type nanoClient struct {
	cc *grpc.ClientConn
}

func NewNanoClient(cc *grpc.ClientConn) NanoClient {
	return &nanoClient{cc}
}

func (c *nanoClient) BlocksInfo(ctx context.Context, in *BlocksInfoRequest, opts ...grpc.CallOption) (*BlocksInfoReply, error) {
	out := new(BlocksInfoReply)
	err := c.cc.Invoke(ctx, "/nanoproto.Nano/BlocksInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NanoServer is the server API for Nano service.
type NanoServer interface {
	BlocksInfo(context.Context, *BlocksInfoRequest) (*BlocksInfoReply, error)
}

// UnimplementedNanoServer can be embedded to have forward compatible implementations.
type UnimplementedNanoServer struct {
}

func (*UnimplementedNanoServer) BlocksInfo(ctx context.Context, req *BlocksInfoRequest) (*BlocksInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlocksInfo not implemented")
}

func RegisterNanoServer(s *grpc.Server, srv NanoServer) {
	s.RegisterService(&_Nano_serviceDesc, srv)
}

func _Nano_BlocksInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlocksInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NanoServer).BlocksInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nanoproto.Nano/BlocksInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NanoServer).BlocksInfo(ctx, req.(*BlocksInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Nano_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nanoproto.Nano",
	HandlerType: (*NanoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BlocksInfo",
			Handler:    _Nano_BlocksInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nanoproto.proto",
}
