// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	usclient "github.com/alvistar/gonano/internal/usclient"
	mock "github.com/stretchr/testify/mock"
)

// IUSClient is an autogenerated mock type for the IUSClient type
type IUSClient struct {
	mock.Mock
}

// Get provides a mock function with given fields: request
func (_m *IUSClient) Get(request []byte) ([]byte, error) {
	ret := _m.Called(request)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Init provides a mock function with given fields: conf
func (_m *IUSClient) Init(conf *usclient.ConfNode) {
	_m.Called(conf)
}
