// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	nanoipc "github.com/alvistar/gonano/pkg/nanoipc"
)

// INanoClient is an autogenerated mock type for the INanoClient type
type INanoClient struct {
	mock.Mock
}

// Get provides a mock function with given fields: request
func (_m *INanoClient) Get(request []byte) ([]byte, *nanoipc.Error) {
	ret := _m.Called(request)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 *nanoipc.Error
	if rf, ok := ret.Get(1).(func([]byte) *nanoipc.Error); ok {
		r1 = rf(request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*nanoipc.Error)
		}
	}

	return r0, r1
}

// Init provides a mock function with given fields:
func (_m *INanoClient) Init() {
	_m.Called()
}
