// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// INanoClient is an autogenerated mock type for the INanoClient type
type INanoClient struct {
	mock.Mock
}

// Get provides a mock function with given fields: request
func (_m *INanoClient) Get(request []byte) ([]byte, error) {
	ret := _m.Called(request)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Init provides a mock function with given fields:
func (_m *INanoClient) Init() {
	_m.Called()
}
